logging.level.org.curryware=DEBUG

spring.datasource.driver-class-name=org.postgresql.Driver

# Allow app to start even if database is unavailable
spring.datasource.hikari.initialization-fail-timeout=-1