name: curryware-java-api-server Build
on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4.2.2
        uses: actions/checkout@v4.2.2
      - name: Setup QEMU v3.6.0
        uses: docker/setup-qemu-action@v3.6.0

      - name: Login to Docker v3.40
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Setup Docker Buildx v3.10.0
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build Docker Image
        run: |
          docker buildx build --push -t scotcurry4/curryware-java-api-server:${{ github.run_number }} \
          --platform linux/amd64 \
          --build-arg DD_VERSION=${{ github.run_number}} \
          --build-arg DD_GIT_REPOSITORY_URL="github.com/scotcurry/curryware-java-api-server" \
          --build-arg DD_GIT_COMMIT_SHA=${{ github.sha }} \
          -f Dockerfile .
