name: curryware-java-api-server Build
on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4.2.2
        uses: actions/checkout@v4.2.2
      - name: Setup QEMU v3.6.0
        uses: docker/setup-qemu-action@v3.6.0

      - name: Login to Docker v3.40
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - name: Setup Docker Buildx v3.10.0
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build Docker Image
        run: |
          docker buildx build --push -t scotcurry4/curryware-java-api-server:${{ github.run_number }} \
          --platform linux/amd64 \
          --build-arg DD_VERSION=${{ github.run_number}} \
          --build-arg DD_GIT_REPOSITORY_URL="github.com/scotcurry/curryware-java-api-server" \
          --build-arg DD_GIT_COMMIT_SHA=${{ github.sha }} \
          -f Dockerfile .

      # Check out the K8s manifest files for updating
      - name: Get manifest files
        uses: actions/checkout@v4
        with:
          repository: 'scotcurry/k8s-manifests'
          path: '${{ github.workspace }}/k8s-manifests'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: 'main'
      - run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/k8s-manifests
          ls ${{ github.workspace }} -la
          # sed pattern to update manifest versions - 's/version: \"[[:digit:]]*\"/version: \"20\"/g'
          # Site to test sed commands - https://sed.js.org/
          echo 'Setting Version: ${{ github.run_number }}'
          sed -i -e 's/version: \"[[:digit:]]*\"/version: \"${{ github.run_number }}\"/g' ${{ github.workspace }}/k8s-manifests/curryware-fantasy/curryware-java-api-server-deployment.yaml
          echo 'Updating image version'
          sed -i -e 's/scotcurry4\/curryware-java-api-server\:[[:digit:]]*/scotcurry4\/curryware-java-api-server\:${{ github.run_number }}/g' ${{ github.workspace }}/k8s-manifests/curryware-fantasy/curryware-java-api-server-deployment.yaml
          cat ${{ github.workspace }}/k8s-manifests/curryware-fantasy/curryware-java-api-server-deployment.yaml
          echo "Committed curryware-java-api-server-deployment.yaml $(date +"%Y-%m-%d %T") - Short SHA: ${{ github.sha }}" > commit_file.txt
          git config user.name "scotcurry"
          git config user.email "scotcurry4@gmail.com"
          git commit -a -F commit_file.txt
          git push
